#!/usr/bin/env python
import sys
import socket
import time
import subprocess
import ConfigParser

from munin import MuninClient

def facterconfig(file):
    c=ConfigParser.ConfigParser()
    if c.read(file):
        if c.has_section('facter'):
                append=c.get('facter','append')
        else:
                append=False
    else:
        append=False
    return append

def facter2dict( lines ):
        res = {}
        for line in lines:
                k, v = line.split(' => ')
                res[k] = v.rstrip()
        return res

def facter():
        p = subprocess.Popen( ['facter','-p'], stdout=subprocess.PIPE )
        p.wait()
        lines = p.stdout.readlines()
        return facter2dict( lines )

def facterstringfromconfig(file):
    config=facterconfig(file)
    if config != False:
        to_append=config.split('.')
        f=facter()
        append=''
        for fact in to_append:
            append+=f[fact]+'.'
    else:
        append=socket.gethostname()+'.'
    return append

def send_to_carbon(message,file='./config.ini'):
    c=ConfigParser.ConfigParser()
    if c.read(file):
        if c.has_section('carbon'):
                host=c.get('carbon','host')
                port=c.get('carbon','port')
                sock = socket.socket()
                sock.connect((host, int(port)))
                sock.sendall(message)
                sock.close()
        else:
                return False
    else:
        return False

while True:
        m=MuninClient('127.0.0.1')
        append=facterstringfromconfig('./config.ini')
        list=m.list()
        for item in list:
                values=m.fetch(item)
                for key in values:
                        message = 'servers'+'.'+append+item+'.'+key+' '+values[key]+' %d\n' % int(time.time())
                        send_to_carbon(message)

        time.sleep( 60 )
